# Generated by Django 2.1.5 on 2019-02-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='address',
            field=models.CharField(default='Не указано', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='city',
            field=models.CharField(default='Не указано', max_length=30),
        ),
        migrations.AddField(
            model_name='article',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='article',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
